### ISSUE TITLE
app is showing mmol/L but mg/dl configured.

### ISSUE THREAD

**Issue by oschumac** [mddub/urchin-cgm#8]
All your pictures showing mg/dl but app does not react on configuration changes, always shows mmol/L.
.

**Comment by mddub** [comment]
I'm sorry, what platform are you on? Can you please try the latest version of the pbw, and if this issue persists, can you give some steps to reproduce? I find the mg/dL / mmol/L toggle works as expected on my iPhone 5S + Pebble Classic.

**Comment by oschumac** [comment]
I d use pebble and pebble steel on on android kitkat. I will try latest version tonight.

**Comment by oschumac** [comment]
Hi, i tested 0.0.5 . For any reason the app won't start.
Also the settings page won#t start it shows an github 404 error.
I did a factory reset and reinstall, but same issue, Any Ideas ?

**Comment by mddub** [comment]
- I was able to confirm the mg/dL issue you reported on my Android tablet running 5.1.1 (Lollipop). Thanks for reporting it! I believe I've fixed the issue in https://github.com/mddub/urchin-cgm/commit/8f390f. Please let me know if it fixes it for you once you get the watchface running again.
- What do you mean by "the app won't start"? It crashes when it opens, or it shows a blank screen, or it shows the watchface but no data?
- If you're seeing a GitHub 404 error, the most likely explanation is that you are running 0.0.3 or earlier. The app was renamed from nightscout-graph-pebble to urchin-cgm at 0.0.4, so older versions point to https://mddub.github.io/nightscout-graph-pebble/config/ (which 404s) instead of https://mddub.github.io/urchin-cgm/config/.
  
  Make sure you download this pbw file:
  
  https://raw.githubusercontent.com/mddub/urchin-cgm/master/release/urchin-cgm.pbw
- If you're still having trouble, would you mind sending me your phone logs when the app is opening or when the configuration page is closed (mark@warkmilson.com)? You don't need to install anything special, but you need to connect to your phone from CloudPebble.
  1. Go to https://cloudpebble.net/ and log in with your Pebble account.
  2. Click "Create" and make a blank project based on any of the templates (it doesn't matter what it's named or which template you use, as long as it's not the "Empty project" template).
  3. Open the Developer Connection on your Pebble app.
  4. Go to Compilation, then click "Run Build".
  5. Under Compilation, click the "Phone" tab, then click "View App Logs".
  6. Exit and enter the watchface and you should see log messages appear.

Thanks.

**Comment by oschumac** [comment]
Hi, i have tested the latest and greatesd. Running now perfect.
Thx for support and the really nice app.
One more question if i choose custom URL. Which format is it. Do you have an excample ?

CU Oliver

**Comment by mddub** [comment]
Custom URL is expected to be text. A couple ways of using it are to run a web server which returns text based on data pulled from the Nightscout API (or directly from Mongo), or to run a process somewhere (e.g. a phone or Raspberry Pi) which uploads a text file to a sever.
